13.0 mig product variant sale price
druidoo-dev/product-variant pull request #1
Opened 2020-02-04 12:31 UTC by chetanrdhaduk

Task URL:
https://www.druidoo.io/web#id=1522&action=367&model=project.task&view_type=form&menu_id=237

2020-02-04 12:59 UTC, ivantodorovich requested changes

2020-02-04 12:59 UTC, ivantodorovich commented on product_variant_sale_price/__manifest__.py
> +    "author": "Tecnativa, " "Odoo Community Association (OCA), Druidoo",
Unfortunately, migrating a module does not make us an author.
Please remove this :)

2020-02-04 13:01 UTC, ivantodorovich requested changes
After you make this change, please squash this new commit with the Migration to 13.0 one

This looks good :+1: 
I'll test it locally and if it works we push to oca

2020-02-04 13:04 UTC, ivantodorovich commented
Another thing to do is squashing all the translation commits into a single one, to clean the history.

> Squash administrative commits (if any) with the previous commit for reducing commit noise. They are named as "[UPD] README.rst", "[UPD] Update $MODULE.pot", "Update translation files" and similar names, and comes from OCA-git-bot, oca-travis or oca-transbot.

2020-02-04 14:05 UTC, ivantodorovich commented
In `13.0` we have this "Extra prices" link and it doesn't look good when we hide the price field.

What if we keep the field label `<label for=".."/>` and add an inline comment saying prices are managed at product variant level?

That way we can keep the link, and it's going to look much better

I mean a message similar to this one, with a link to the product variants action:
![image](https://user-images.githubusercontent.com/1914185/73751414-5adb2d00-475f-11ea-8b1f-ccc302a352aa.png)





--------





![image](https://user-images.githubusercontent.com/1914185/73751204-e7d1b680-475e-11ea-8662-16536ed7620f.png)

2020-02-04 15:24 UTC, ivantodorovich commented
Also hide the price on kanban when there are variants:

![image](https://user-images.githubusercontent.com/1914185/73751864-359aee80-4760-11ea-9794-f353049881de.png)

2020-02-05 09:34 UTC, ivantodorovich commented
I'm on a variant, and I see the message. Also I'm not able to edit the price there:
![image](https://user-images.githubusercontent.com/1914185/73829346-130de180-4803-11ea-9d3b-f69172a96aae.png)

2020-02-05 09:42 UTC, closed without merging

2020-02-05 09:52 UTC, chetanrdhaduk commented
I will remove the message from the variant, As per the functionality in v12 we can not edit the list price directly, We have to update it through "Fix Price" field.